version: '3.8'

services:
  iot-gateway:
    build: ./iot-gateway
    container_name: iot-gateway
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    networks:
      - iot-network

  sensor_service:
    build: ./sensor_service
    container_name: sensor_service
    ports:
      - "8001:8001"
    networks:
      - iot-network
    depends_on:
      - postgres_sensor_db
    environment:
      DATABASE_URL: ${DATABASE_URL}  # Usando la variable de entorno definida en .env

  postgres_sensor_db:
    image: postgres:13
    container_name: postgres_sensor_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Usando la variable de entorno definida en .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Usando la variable de entorno definida en .env
      POSTGRES_DB: ${POSTGRES_DB}  # Usando la variable de entorno definida en .env
    ports:
      - "5433:5432"
    networks:
      - iot-network
    volumes:
      - sensor_db_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./iot-gateway/mosquitto/config:/mosquitto/config
    networks:
      - iot-network
    retart: always

networks:
  iot-network:
    driver: bridge

volumes:
  sensor_db_data:
